accuweather can open a window a 3 day forecast, mus and accuweather now have color, better media handling

diff --git a/accuweather b/accuweather
--- a/accuweather
+++ b/accuweather
@@ -1,21 +1,32 @@
 #!/bin/sh 
 
+. ~/.cache/wal/colors.sh
+
 # 0:F
 # 1:C
 METRIC=0
- 
-if [ -z "$1" ]; then
-echo
-echo "USAGE: weather.sh <locationcode>"
-echo
-exit 0;
-fi
 
-curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=$METRIC\&locCode\=$1 | \grep "Currently:" | sed 's/\(<title>\|<\/title>\)//g' | awk '{$1="";print}' > /tmp/weather
+case $BLOCK_BUTTON in
+    1)
+        $TERMINAL --class=float --hold -e curl wttr.in
+        ;;
+    2)
+        ;;
+    3)
+        ;;
+    4)
+        ;;
+    5)
+        ;;
+esac
+ 
+[ -z "$1" ] && echo "zipcode required!" && exit 1
+
+curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=$METRIC\&locCode\="$1" | grep "Currently:" | sed 's/\(<title>\|<\/title>\)//g' | awk '{$1="";print}' > /tmp/weather
 
 current_weather=$(awk -F':' '{print $1}' /tmp/weather | xargs)
 
-temperature=$(awk -F':' '{print $2}' /tmp/weather | xargs)
+temperature=$(awk -F':' '{print $2}' /tmp/weather | xargs | sed 's/F/°F/')
 
 case $current_weather in
     "Sunny")
@@ -107,5 +118,5 @@ case $current_weather in
         ;;
 esac
 
-# printf "<span>%s</span>\n" "$icon $temperature"
-echo "$icon  $temperature"
+printf "<span color='%s'>%s</span>  <span color='%s'>%s</span>\n" \
+    "$color9" "$icon" "$color5" "$temperature"
